# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-09 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0618_auto_20220622_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectiontypeapprovaldocument',
            options={'verbose_name': 'CM_Inspection type approval document', 'verbose_name_plural': 'CM_Inspection type approval documents'},
        ),
        migrations.AlterModelOptions(
            name='sanctionoutcomewordtemplate',
            options={'ordering': ['-id'], 'verbose_name': 'CM_Wildlife Compliance Template', 'verbose_name_plural': 'CM_Wildlife Compliance Templates'},
        ),
    ]
