# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0619_auto_20220628_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlistquestion',
            name='help_text_url',
            field=models.CharField(default='www.google.com', max_length=200),
        ),
    ]
