# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0624_auto_20240123_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offence_allocated_group', to='wildlifecompliance.ComplianceManagementSystemGroup'),
        ),
    ]
