# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0625_offence_allocated_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_allocated_group', to='wildlifecompliance.ComplianceManagementSystemGroup'),
        ),
    ]
