# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-20 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0627_auto_20240220_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_allocated_group', to='wildlifecompliance.ComplianceManagementSystemGroup'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_district', to='wildlifecompliance.District'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_region', to='wildlifecompliance.Region'),
        ),
    ]
