# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-07 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0628_auto_20240220_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_outcome_allocated_group', to='wildlifecompliance.ComplianceManagementSystemGroup'),
        ),
    ]
