# Generated by Django 3.2.5 on 2025-02-04 07:31

import django.contrib.auth.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import wildlifecompliance.components.applications.models
import wildlifecompliance.components.legal_case.models
import wildlifecompliance.components.licences.models
import wildlifecompliance.components.main.models
import wildlifecompliance.components.offence.models
import wildlifecompliance.components.returns.models
import wildlifecompliance.components.sanction_outcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0629_sanctionoutcome_allocated_group'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activitypermissiongroup',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RenameField(
            model_name='legalcaseperson',
            old_name='emailuser_ptr',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='licencecategory',
            old_name='licencetype_ptr_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='organisation_inspected',
            new_name='organisation_inspected_id'
        ),
        migrations.RenameField(
            model_name='offender',
            old_name='organisation',
            new_name='organisation_id',
        ),
        migrations.AddField(
            model_name='inspection',
            name='organisation_inspected_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Ledger Organisation ID'),
        ),
        migrations.AlterField(
            model_name='actiontakendocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='comment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.applications.models.update_application_doc_filename),
        ),
        migrations.AlterField(
            model_name='applicationformdatarecord',
            name='component_attribute',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationformdatarecord',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationlogdocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.applications.models.update_application_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='applicationselectedactivity',
            name='activity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationselectedactivity',
            name='additional_licence_info',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='applicationselectedactivity',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='applicationselectedactivitypurpose',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='applicationselectedactivitypurpose',
            name='purpose_species_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='artifactcommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='artifactdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='briefofevidencedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='callemail',
            name='dead',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='callemail',
            name='euthanise',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='callemaildocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='callemaillogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='complianceformdatarecord',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancemanagementsystemgroup',
            name='name',
            field=models.CharField(choices=[('call_email_triage', 'Call Email Triage'), ('officer', 'Officer'), ('inspection_officer', 'Inspection Officer'), ('manager', 'Manager'), ('volunteer', 'Volunteer'), ('infringement_notice_coordinator', 'Infringement Notice Coordinator'), ('prosecution_coordinator', 'Prosecution Notice Coordinator'), ('prosecution_manager', 'Prosecution Manager'), ('prosecution_council', 'Prosecution Council'), ('compliance_management_read_only', 'Compliance Management Read Only'), ('compliance_management_call_email_read_only', 'Compliance Management Call Email Read Only'), ('compliance_management_approved_external_user', 'Compliance Management Approved External User'), ('compliance_admin', 'Compliance Admin'), ('licensing_admin', 'Licensing Admin')], max_length=200),
        ),
        migrations.AlterField(
            model_name='complianceuserintelligencedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='courthearingnoticedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='courtoutcomedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.legal_case.models.update_court_outcome_doc_filename),
        ),
        migrations.AlterField(
            model_name='inspectioncommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspectiondocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspectionformdatarecord',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreportdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='schema',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='inspectiontypeapprovaldocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='issuancedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='legalcasecommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='legalcasedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='legalcasegenerateddocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='licenceactivity',
            name='schema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='licencedocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.licences.models.update_licence_doc_filename),
        ),
        migrations.AlterField(
            model_name='licencepurpose',
            name='fields',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='licencepurpose',
            name='schema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='licencespecies',
            name='data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='masterlistquestion',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='offencecommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='offencedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.offence.models.update_offence_doc_filename),
        ),
        migrations.AlterField(
            model_name='offender',
            name='organisation_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Ledger Organisation ID'),
        ),
        migrations.AlterField(
            model_name='organisationintelligencedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='identification',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to='wildlifecompliance/organisation/requests/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='physicalartifactformdatarecord',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalartifacttype',
            name='details_schema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='physicalartifacttype',
            name='storage_schema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='prosecutionbriefdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='prosecutionnoticedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='purposespecies',
            name='species',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rendererdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='schema',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='returnlogdocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.returns.models.update_returns_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='returnrow',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returntype',
            name='data_descriptor',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sanctionoutcomecommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sanctionoutcomedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.sanction_outcome.models.update_compliance_doc_filename),
        ),
        migrations.AlterField(
            model_name='sanctionoutcomewordtemplate',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.main.models.update_sanction_outcome_word_filename),
        ),
        migrations.AlterField(
            model_name='sectiongroup',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='temporarydocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='wildcarespeciessubtype',
            name='wildcare_species_type',
            field=models.ForeignKey(limit_choices_to={'show_species_name_textbox': False}, on_delete=django.db.models.deletion.CASCADE, related_name='wildcare_species_sub_types', to='wildlifecompliance.wildcarespeciestype'),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='extracted_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
