# Generated by Django 3.2.5 on 2025-02-17 03:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0630_auto_20250204_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencecategory',
            name='act',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='authority',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='is_renewable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.licencecategory'),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='short_name',
            field=models.CharField(blank=True, help_text='The display name that will show in the dashboard', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='version',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='licencecategory',
            unique_together={('short_name', 'version')},
        ),
    ]
