# Generated by Django 5.2 on 2025-04-24 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '__first__'),
        ('inspection', '__first__'),
        ('legal_case', '__first__'),
        ('wildlifecompliance', '0632_alter_legalcaseperson_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentartifact',
            name='legal_cases',
            field=models.ManyToManyField(related_name='legal_case_document_artifacts', through='wildlifecompliance.DocumentArtifactLegalCases', through_fields=('document_artifact', 'legal_case'), to='wildlifecompliance.legalcase'),
        ),
        migrations.AlterField(
            model_name='documentartifact',
            name='people_attending',
            field=models.ManyToManyField(related_name='document_artifact_people_attending', through='artifact.DocumentArtifactPeopleAttending', through_fields=('documentartifact', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_team',
            field=models.ManyToManyField(blank=True, through='inspection.InspectionTeam', through_fields=('inspection', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='associated_persons',
            field=models.ManyToManyField(related_name='legal_case_associated_persons', through='legal_case.LegalCaseAssociatedPerson', through_fields=('legalcase', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licencecategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='physicalartifact',
            name='legal_cases',
            field=models.ManyToManyField(related_name='legal_case_physical_artifacts', through='wildlifecompliance.PhysicalArtifactLegalCases', through_fields=('physical_artifact', 'legal_case'), to='wildlifecompliance.legalcase'),
        ),
        migrations.CreateModel(
            name='FileExtensionWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The file extension without the dot, e.g. jpg, pdf, docx, etc', max_length=16)),
                ('model', models.CharField(default='all', max_length=255)),
            ],
            options={
                'unique_together': {('name', 'model')},
            },
        ),
    ]
