# Generated by Django 5.2 on 2025-04-24 07:05

import django.core.files.storage
import wildlifecompliance.components.applications.models
import wildlifecompliance.components.licences.models
import wildlifecompliance.components.returns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0634_alter_actiontakendocument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.applications.models.update_application_doc_filename),
        ),
        migrations.AlterField(
            model_name='applicationlogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.applications.models.update_application_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='licencedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.licences.models.update_licence_doc_filename),
        ),
        migrations.AlterField(
            model_name='returnlogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.returns.models.update_returns_comms_log_filename),
        ),
    ]
