# Generated by Django 5.2 on 2025-04-28 02:45

import django.core.files.storage
import wildlifecompliance.components.call_email.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0635_alter_applicationdocument__file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemaillogdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.call_email.models.update_call_email_comms_log_filename),
        ),
    ]
