# Generated by Django 5.2 on 2025-05-29 00:40

import django.core.files.storage
import wildlifecompliance.components.inspection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0636_alter_callemaillogdocument__file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontypeapprovaldocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to=wildlifecompliance.components.inspection.models.update_inspection_type_approval_doc_filename),
        ),
    ]
