# Generated by Django 5.2 on 2025-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0637_alter_inspectiontypeapprovaldocument__file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReportHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
