# Generated by Django 5.2 on 2025-06-16 01:59

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0638_returnreporthash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offender',
            name='person',
        ),
        migrations.AddField(
            model_name='offender',
            name='address_country',
            field=django_countries.fields.CountryField(blank=True, default='AU', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='offender',
            name='address_locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suburb / Town'),
        ),
        migrations.AddField(
            model_name='offender',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='offender',
            name='address_state',
            field=models.CharField(blank=True, default='WA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offender',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='offender',
            name='dob',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='offender',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offender',
            name='first_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Given name(s)'),
        ),
        migrations.AddField(
            model_name='offender',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='offender',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile number'),
        ),
        migrations.AddField(
            model_name='offender',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number'),
        ),
    ]
