# Generated by Django 5.2 on 2025-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0639_remove_offender_person_offender_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offender',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
