# Generated by Django 5.2 on 2025-06-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0640_alter_offender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offender',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
