# Generated by Django 5.2 on 2025-06-24 08:23

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0641_alter_offender_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenderPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(max_length=128, null=True, verbose_name='Given name(s)')),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile number')),
                ('address_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('address_locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suburb / Town')),
                ('address_state', models.CharField(blank=True, default='WA', max_length=255, null=True)),
                ('address_country', django_countries.fields.CountryField(blank=True, default='AU', max_length=2, null=True)),
                ('address_postcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'CM_Offender_Person',
                'verbose_name_plural': 'CM_Offender_Persons',
            },
        ),
        migrations.RemoveField(
            model_name='offender',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='address_locality',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='address_postcode',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='address_state',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='email',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='offender',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offender_person', to='wildlifecompliance.offenderperson'),
        ),
    ]
