# Generated by Django 5.2.4 on 2025-07-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0637_alter_inspectiontypeapprovaldocument__file'),
        ('wildlifecompliance', '0642_offenderperson_remove_offender_address_country_and_more'),
    ]

    operations = [
    ]
