# Generated by Django 5.2.9 on 2026-02-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0643_merge_20250716_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='processing_status',
            field=models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('draft', 'Current'), ('future', 'Future'), ('with_curator', 'With Curator'), ('accepted', 'Accepted'), ('payment', 'Awaiting Payment'), ('discarded', 'Expired'), ('expired', 'Expired')], default='future', max_length=20),
        ),
    ]
