# Generated by Django 5.2.9 on 2026-02-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0645_wildlifesystempermission_wildlifesystemgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WildlifeSystemGroup',
        ),
        migrations.DeleteModel(
            name='WildlifeSystemPermission',
        ),
    ]
