# Generated by Django 5.2.9 on 2026-02-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0646_delete_wildlifesystemgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeSystemPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('codename', models.CharField(max_length=100, verbose_name='codename')),
            ],
            options={
                'verbose_name': 'wildlife system permission',
                'verbose_name_plural': 'wildlife system permissions',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='WildlifeSystemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, to='wildlifecompliance.wildlifesystempermission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'wildlife system group',
                'verbose_name_plural': 'wildlife system groups',
            },
        ),
    ]
