# Generated by Django 5.2.9 on 2026-02-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wildlifecompliance', '0648_wildlifesystemgroupuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypermissiongroup',
            name='group_ptr',
            field=models.OneToOneField(db_column='group_ptr_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='auth.group'),
        ),
    ]
