# Generated by Django 5.2.9 on 2026-02-10 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0649_alter_activitypermissiongroup_group_ptr'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activitypermissiongroup',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='activitypermissiongroup',
            name='group_ptr',
            field=models.OneToOneField(db_column='group_ptr_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='wildlifecompliance.wildlifesystemgroup'),
        ),
    ]
