# Generated by Django 5.2.12 on 2026-04-15 02:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0650_alter_activitypermissiongroup_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='identification',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/wildlifecompliance/private-media/'), upload_to='wildlifecompliance/organisation/requests/%Y/%m/%d'),
        ),
    ]
